### PR TITLE
Fix x-codeSamples load when switching language tabs

### PR DESCRIPTION
**Pull request by lucasassisrosa**
## Description

Use merged languages to have updated set of languages on change language and code tabs

## Motivation and Context

Fix an issue when switching from a non custom code sample language tab to a custom code sample one

## How Has This Been Tested?

https://docusaurus-openapi-36b86--pr660-xou63k6x.web.app/petstore/add-pet, switching from Java to PHP for example

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sserrata** [comment]
Hi @lucasassisrosa, I noticed that I see an empty code snippet sometimes when switching between languages. A reload seems to always correct the issue but switching languages re-introduces it.

Screenshot 2024-01-19 at 8 54 01 AM

**Comment by lucasassisrosa** [comment]
> Hi @lucasassisrosa, I noticed that I see an empty code snippet sometimes on first load/render. A reload seems to always correct the issue.
> 
> Screenshot 2024-01-19 at 8 54 01 AM

thanks. Let me check to fix that

**Comment by lucasassisrosa** [comment]
> I noticed that I see an empty code snippet sometimes on first load/render

@sserrata I tried the following scenarios on the [PR Preview](https://docusaurus-openapi-36b86--pr706-6jdkvoi7.web.app/petstore/add-pet) and couldn't replicate the empty code snippet issue:

- landing on the page with no `docusaurus.tab.code-samples` language set then clicking on `php` tab
- landing on the page with `docusaurus.tab.code-samples` set to `php`

Could you share the scenario that uncovers the issue?

**Comment by lucasassisrosa** [comment]
> Could you share the scenario that uncovers the issue?

Maybe it's an issue with the localStorage `docusaurus.tab.code-samples` language that I cannot reproduce. Anyway, I added a piece of code to load code sample source from `language` on `codeSampleCodeText` initial state

**Comment by lucasassisrosa** [comment]
> > Could you share the scenario that uncovers the issue?
> 
> Maybe it's an issue with the localStorage `docusaurus.tab.code-samples` language that I cannot reproduce. Anyway, I added a piece of code to load code sample source from `language` on `codeSampleCodeText` initial state

@sserrata I have identified more bugs when switching language tabs with multiple code samples. Working on it

**Pull request merged**
