### PR TITLE
Support anyOf/oneOf schema descriptions

### PR DESCRIPTION
**Pull request by sserrata**
## Description

Addresses #887

### CODE REVIEW

**Comment by sserrata** [comment]
@IanVS thoughts?

**Comment by IanVS** [comment]
Sorry, where should I be looking in the demo?

**Comment by sserrata** [comment]
> Sorry, where should I be looking in the demo?

Right here, under the `pet` property: https://docusaurus-openapi-36b86--pr897-n05ye48p.web.app/petstore/create-user

**Comment by IanVS** [comment]
Looks good to me, though maybe a class name that could be targeted for styling would be nice.

**Review by IanVS — APPROVED** [review]

**Pull request merged**
