### PR TITLE
Allow "none" option for categoryLinkSource

### PR DESCRIPTION
**Pull request by IanVS**
## Description

This adds a new `"none"` option for `categoryLinkSource`.  I didn't actually need to change any logic, only allow the value in the schema, because the link config defaults to `undefined` already.

## Motivation and Context

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/discussions/434

## How Has This Been Tested?

I made the change locally in my node_modules, and it did exactly what I hoped it would.  :-D

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed. (I didn't run them)

### CODE REVIEW

**Review by sserrata — APPROVED** [review]
LGTM but, for some reason, I am not seeing your changes to documented `categoryLinkSource` options reflected in the preview.

**Comment by sserrata** [comment]
As, disregard, I see now that the change was added only to the README. No worries, we can add it later. Thanks!

**Comment by IanVS** [comment]
Oh, where else should it have been added?

**Comment by sserrata** [comment]
It's currently spread across the top-level README, the `docusaurus-plugin-openapi-docs` packages README and the intro doc located in the demo site. I was a bit behind on adding the `hideSendButton` option so I went ahead and updated them in  #463.

**Pull request merged**
