### PR TITLE
[V2] OpenAPI 2.0 Preview

### PR DESCRIPTION
**Pull request by blindaa121**
## Description

Long-standing PR for upcoming `v2.0.0` release

Preview: https://docusaurus-openapi-36b86--pr439-hycqr78u.web.app/petstore/add-pet

### Completed Child PR's:

- [x] #557
- [x] #540 
- [x] #537
- [x] #534
- [x] #533 
- [x] #531
- [x] #524 
- [x] #471
- [x] #431
- [x] #429
- [x] #450
       #389 
- [x] #476

### CODE REVIEW

**Comment by smeng9** [comment]
Hi, are there additional child PR's in flight or is the 2.0.0 feature complete?

**Comment by sserrata** [comment]
Hi @smeng9, it is considered feature complete as of now.

**Comment by smeng9** [comment]
Hi @sserrata, Do we have a timeline for the stable release of 2.0?

**Comment by sserrata** [comment]
@smeng9, hoping to have it rolled out by mid-to-late September, once we have time to focus on this project again. For now, the v2.0.0-beta should be considered "stable enough" for use in production - not anticipating any major breaking changes between now and stable release.

**Comment by IanVS** [comment]
Hi, is there any chance that version 2 of this plugin can be updated to support Docusaurus 3? https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/654. And so that users can plan for their upgrades, maybe you can give an estimate of when you expect you might have time to finish working on the new version?

Thanks as always!

**Pull request closed without merging**
