### PR TITLE
[Bug] Implement selective escape for sanitizing titles and descriptions

### PR DESCRIPTION
**Pull request by sserrata**
## Description

See #299  for background.

This PR implements selective replace for `<` and `>` characters in order to preserve support for inline HTML. Previously, `lodash` `escape()` was being used to HTML-encode all special characters, which broke inline-HTML.

## Motivation and Context

Renders titles and descriptions as intended, including HTML.

## How Has This Been Tested?

Tested with Petstore and IOT APIs but more testing will be welcomed to ensure no regression bugs are introduced.

Additional testing with Threat Prevention API.

> Note: during IOT testing I found that there were improperly formatted tags, like `<b> <b/>` which I needed to fix in order to successfully build. Previously, these issues were being masked.

### CODE REVIEW

**Comment by blindaa121** [comment]
@sserrata Tested with IOT and the expected behavior looks great. Although, I did notice a similar issue for our `<ParamsItem />` and `<SchemaItem />` components. Dug into this a bit and the good news is that `<ReactMarkdown />` can accept a `rehypePlugin` prop, which I've tested locally with the [rehype-raw](https://github.com/rehypejs/rehype-raw]) plugin to achieve the desired behavior.

Before:
Screen Shot 2022-10-17 at 2 56 06 PM

After: 
Screen Shot 2022-10-17 at 2 54 03 PM

I can push up these changes if they check out 👍

**Comment by sserrata** [comment]
Nice! Feel free to push the changes.

**Comment by sserrata** [comment]
Just need to make sure we have enough coverage of HTML and any potential Docusaurus-specific tags.

**Comment by blindaa121** [comment]
> Just need to make sure we have enough coverage of HTML and any potential Docusaurus-specific tags.

I believe the `rehype-raw` plugin provides enough HTML coverage, but not entirely sure on potential Docusaurus-specific tags.

**Pull request merged**
