### PR TITLE
Remove react nextui dependency in v2.0.0

### PR DESCRIPTION
**Pull request by Mikescops**
## Description

This is a **suggestion** to fix bugs and avoid loading large library.

Remove NextUI library from v2.0.0.

## Motivation and Context

NextUI is a giant library and it's only used to display a loader that can be used in simpler way.

This dependency was creating side effects that weren't resolved: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/608

## How Has This Been Tested?

This was tested with the demo and a side project, using both Yarn and PNPM8.

## Screenshots (if appropriate)

image

image

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Mikescops** [comment]
Either we remove it, or we bump the dependency to its latest version (here it was using the beta).

Note: Loading is probably now named Spinner: https://nextui.org/docs/components/spinner

**Comment by sserrata** [comment]
Hi @Mikescops, thanks for the suggestion/tip. I agree that there are other ways to render a loading spinner without depending on large libraries. We'll look into refactoring it.

**Comment by Mikescops** [comment]
> Hi @Mikescops, thanks for the suggestion/tip. I agree that there are other ways to render a loading spinner without depending on large libraries. We'll look into refactoring it.

Thanks @sserrata feel free to reuse this PR or create new one/delete this one.

**Review by blindaa121 — APPROVED** [review]

**Comment by Mikescops** [comment]
@sserrata Should this be merged now that it's approved?

**Pull request merged**
