### PR TITLE
Add support for security vendor extensions

### PR DESCRIPTION
**Pull request by sserrata**
## Description

Adds support for rendering/handling vendor extensions in `securitySchemes`.

## Motivation and Context

Addresses an issue with our Code Security API.

## How Has This Been Tested?

See deploy preview.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by jasikpark** [comment]
I'm curious what extensions this fix is for, if you wouldn't mind sharing?

**Comment by sserrata** [comment]
Hi @jasikpark, the extensions will vary by vendor, but they will all begin with `x-`. Basically, the plugin will now render/include whatever extensions are passed under security schemes.

**Comment by jasikpark** [comment]
ah, ig I was hoping to see an example of what that would look like, but it sounds like extensions are mostly invented and used privately for different apis?

**Comment by sserrata** [comment]
Yes, that's correct. They're are entirely invented. Here's some examples that AWS supports:

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html

**Pull request merged**
