### PR TITLE
Relax dependencies to allow building with 2.1.0.

### PR DESCRIPTION
**Pull request by homotechsual**
## Description

Relaxes the `@docusaurus/theme-common` (and other Docusaurus) dependencies in `docusaurus-theme-openapi-docs` package to allow building against and compatibility with a wider range of `2.*.*` releases in line with Docusaurus' SemVer policy for `2.*` stable releases (minor changes only - should be no breaking changes).

## Motivation and Context

This allows successful building and compatibility with `2.1.0` and all tests pass.

## How Has This Been Tested?

All tests pass including Jest, Cypress (Edge 105 and Firefox) and manual tests.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes if appropriate.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by homotechsual** [comment]
`yarn.lock` in the /demo` folder is out of date it seems but I can't actually get it to update properly on my machine 😕

**Comment by sserrata** [comment]
So, it turns out that `yarn.lock` file under the demo directory is unnecessary, likely generated and pushed by mistake 😅.

Also, I think the strategy would be to relax the dependencies in such a way that it's compatible with any release starting from `2.0.1` until the end of the 2.x train. Users could define `resolutions` under `package.json` to "pin" to a specific version in that train if needed.

**Comment by homotechsual** [comment]
I think we can do any `2.*.*` upto `3.*.*` but I'm not sure there's a version constraint that sets a minimum minor version?

**Comment by sserrata** [comment]
I think we could accomplish that by including the minor release, e.g. `^2.1.0` but doing it that way would exclude `2.0.1`. Essentially, specifying `^2.0.1` will automatically support and upgrade to any 2.x.x release but not 3.x and beyond.

**Comment by homotechsual** [comment]
So I've been playing with version constraints and you could do:

```
>2.0.1 <3.0.0
```

**Pull request closed without merging**
