### PR TITLE
Add documentation for languageTabs and request method labels.

### PR DESCRIPTION
**Pull request by homotechsual**
## Description

This documents setting the languageTabs and customising the request method labels.

## Motivation and Context

Documentation only change to document language tabs and request method label css.

## How Has This Been Tested?

N/A

## Types of changes

- Documentation: Changes to documentation content only.

## Checklist

- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes if appropriate.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by sserrata — CHANGES_REQUESTED** [review]
Looks great! Only a couple of minor changes requested:

* Can we revert `docusaurus.config.js` changes? It appears `powershell` was added although not yet supported.
* Could we rename "customisation" to "customization" for consistency?

**Review by sserrata — CHANGES_REQUESTED** [review]
I just noticed that `languagetabs.md` is still referencing "powershell" in the example. Probably best to clean that up as well. Thanks!

**Comment by sserrata** [comment]
By the way, we can definitely add support for "powershell". I would have already included it but I couldn't find a suitable SVG icon on [DEVICON](https://devicon.dev/).

**Comment by homotechsual** [comment]
There is a PowerShell icon accepted into `DEVICON`'s develop branch!

**Pull request merged**
