### PR TITLE
[UI Enhancement] Move MethodEndpoint from ApiDemoPanel to left doc panel

### PR DESCRIPTION
**Pull request by blindaa121**
## Description

**Preview** https://docusaurus-openapi-36b86--pr429-zmk937lw.web.app/

This PR consists of moving `MethodEndpoint` from the `ApiDemoPanel` into the left doc panel for better readability with longer endpoint paths. The method endpoint now renders directly underneath an API doc's title with the addition of the selected `server` base url. 

## How Has This Been Tested?

Tested with Petstore API

### Desktop | Chrome 
https://user-images.githubusercontent.com/48506502/219767582-215c3869-0d42-4343-84db-c766fb5dfbe7.mov

### Mobile | iPad 9.7"
Screenshot 2023-02-17 at 11 15 01 AM

### Mobile | iPhone 12 Pro
Screenshot 2023-02-17 at 11 14 46 AM

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sserrata** [comment]
Thanks @blindaa121, what are your thoughts on removing the background and padding so it looks more consistent with that side of the API docs?

Screenshot 2023-02-14 at 9 01 56 AM

Also, would it be possible to include the `server` base URL if it's available/set?

**Comment by blindaa121** [comment]
> Thanks @blindaa121, what are your thoughts on removing the background and padding so it looks more consistent with that side of the API docs?
> 
> Screenshot 2023-02-14 at 9 01 56 AM
> 
> Also, would it be possible to include the `server` base URL if it's available/set?

Hi @sserrata, thanks for the suggestion! I think the removal of the background and padding makes sense in terms of consistency with the left API doc page. On another note, I do feel that there should be a subtle level of styling for the endpoint path, perhaps we can forgo the background and use a border with reduced padding instead? ie. 

image

image

As for including the `server` base URL, I think this is doable. I think it may require some digging into if we also wanted to support synching between the `ApiDemoPanel` if a particular base url is selected. Will look into this!

**Comment by sserrata** [comment]
Thoughts on flipping the order of the method/endpoint and deprecation notice? I am not sure which would be more natural?

Screenshot 2023-02-14 at 12 36 30 PM

**Comment by blindaa121** [comment]
> Thoughts on flipping the order of the method/endpoint and deprecation notice? I am not sure which would be more natural?
> 
> Screenshot 2023-02-14 at 12 36 30 PM

Ah good point. In this case, I thought it made a bit more sense to display any warnings at the top-most level. Although, my initial thought was to keep the same ordering, endpoint path directly underneath the title to remain consistent. Comparing them side by side, I'm now leaning towards the latter. 😄

**Comment by blindaa121** [comment]
@sserrata Made some changes and updated the screen cap in the description: 
1. Use of `width: fit-content`
2. Prefix path with `server` url and ensure it syncs with the selected option in `ApiDemoPanel`

**Comment by sserrata** [comment]
Test with javascript disabled:

Screenshot 2023-02-21 at 3 23 27 PM

**Comment by sserrata** [comment]
Test with javascript enabled:

https://user-images.githubusercontent.com/9343811/220450473-838ce8b2-6203-45f1-b8eb-258507a312fb.mov

**Review by sserrata — APPROVED** [review]

**Pull request merged**
