### PR TITLE
[V3] OpenAPI 3.0 Preview

### PR DESCRIPTION
**Pull request by sserrata**
## Description

Long-standing PR for v3.0.0 release.

Preview: https://docusaurus-openapi-36b86--pr660-xyj5psbp.web.app/

## Motivation and Context

Provides support for Docusaurus v3.0.0

> Note: this branch automatically deploys canary releases and will be periodically used to deploy 3.0.0-beta.x releases that can you be used in your project(s). Please check README/homepage/announcements for the latest beta release.

### CODE REVIEW

**Comment by jcwillox** [comment]
Thanks for putting this together, excited to get our docs up and running with Docusaurus 3 👍 
I've just tested it on around 300 endpoints and had no issues with mdx or running it with docusaurus 3, everything appears to work correctly except the JSON syntax highlighting is not working for the response examples and the actual response body after using the send request button, the issue is also present in your preview deployment. For us, it's also not working in the editable request body, although we also had that specific issue in v2, so likely unrelated.

image

**Comment by lucasassisrosa** [comment]
@sserrata can we include Callbacks Support in V3?

**Comment by lucasassisrosa** [comment]
> @sserrata can we include Callbacks Support in V3, please?

https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/700/files

**Comment by lucasassisrosa** [comment]
> > @sserrata can we include Callbacks Support in V3, please?
> 
> https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/700/files

@sserrata I have found an issue when switching from a non custom code sample language tab to a custom code sample one: https://docusaurus-openapi-36b86--pr660-xou63k6x.web.app/petstore/add-pet, switching from Java to PHP for example

Here are the fixes (v2 and v3):

- https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/707
- https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/706

**Comment by mason-at-pieces** [comment]
Any update on when yall will support Docusaurus v3? I assume this is the pr for that?

**Comment by monica-m-ps** [comment]
I'm waiting on this one too 😸 
Until then, 🍿 🕶️

**Comment by mason-at-pieces** [comment]
@sserrata Any idea on a timeline for this getting merged in?

**Comment by sserrata** [comment]
@mason-at-pieces the plan is to continue working toward a stable release with Docusaurus v3 support, although that can be a moving target at times. Merges to this branch/PR automatically deploy canary releases. On occasion, we'll publish a v3.0.0-beta.x release. Either of those can be used in your project(s) as long as you understand they are prereleases. 

FWIW, the plan isn't necessarily to merge this into main - we might instead eventually just promote v3.0.0 to main and archive the current main as v2.0.0, if that makes sense.

**Comment by mason-at-pieces** [comment]
@sserrata I see, thanks for the explanation. May try out the canary but would obviously prefer a stable release. Either way, thanks and I'll do some testing with the canary 👍

**Comment by mason-at-pieces** [comment]
Looking forward to testing the new parsers 🔥

**Comment by ElliotFriend** [comment]
Hi, there @sserrata!

I know the question of "when v3" has been [asked and answered](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/pull/660#issuecomment-2000094277), so I won't bug you with the same thing. I do, however, want to drop some more detailed questions:

1. **Is there a public roadmap or checklist of what remains to be done?** Are any of the GH issues targeted for v3 or anything? Any major blockers at the moment? As you said, it's a "moving target," but I'm curious what work still lies ahead. Because...
2. **I'd love to help! What can I do to pitch in?** We use the plugin for a few different software packages in our docs site, and we're (maybe too?) eager to migrate off of docusaurus v2. I'd be happy to contribute some time and effort to help out with the work. I've gotten _pretty_ ok at the inner-workings of docusaurus, so I hope I might be able to lend a hand.

P.S. The most recent commit, 23c8c01, doesn't seem to have generated a canary/beta release, from what I can tell.

**Pull request closed without merging**
